version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: jp
      POSTGRES_PASSWORD: bla1bla2
      POSTGRES_DB: laravel
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data